# Generated by Django 3.1.1 on 2020-10-25 08:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_comment', models.DateField(default=django.utils.timezone.now)),
                ('comment_content', models.CharField(max_length=100)),
                ('is_report', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=200)),
                ('delivery_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_status', models.BooleanField(default=False)),
                ('delivery_copletion', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Paid_subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('use_points', models.PositiveIntegerField(default=0)),
                ('remaining_points', models.PositiveIntegerField(default=0)),
                ('payment', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TMSeries',
            fields=[
                ('series_id', models.AutoField(primary_key=True, serialize=False)),
                ('series_title', models.CharField(max_length=30)),
                ('introduce', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_paid_subs', models.BooleanField(default=False)),
                ('last_uploaded_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('heart_num_total', models.PositiveIntegerField(default=0)),
                ('views_num_total', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TMText',
            fields=[
                ('text_id', models.AutoField(primary_key=True, serialize=False)),
                ('text_title', models.CharField(max_length=30)),
                ('main_sentence', models.CharField(blank=True, default='Main sentence', max_length=200, null=True)),
                ('text_content', models.CharField(max_length=5000)),
                ('heart_num', models.PositiveIntegerField(default=0)),
                ('comment_num', models.PositiveIntegerField(default=0)),
                ('views_num', models.PositiveIntegerField(default=0)),
                ('date_of_write', models.DateField(default=django.utils.timezone.now)),
                ('text_cover', models.ImageField(default='../static/img/no-image.png', upload_to='covers')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text', to='tomaggeultext.tmseries')),
                ('text_genre', models.ManyToManyField(related_name='text_genre', to='genre.Genre')),
            ],
        ),
    ]
