# Generated by Django 3.1.1 on 2020-10-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomaggeultext', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmtext',
            name='text_cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
    ]
