# Generated by Django 3.1.1 on 2020-10-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomaggeultext', '0002_tmtext_text_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmtext',
            name='text_cover',
            field=models.ImageField(default='defaultImage/no-image.png', upload_to='covers'),
        ),
    ]
