# Generated by Django 3.1.1 on 2020-10-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomaggeultext', '0005_auto_20201017_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmtext',
            name='main_sentence',
            field=models.CharField(blank=True, default='Main sentence', max_length=200, null=True),
        ),
    ]
