# Generated by Django 3.1.1 on 2020-10-24 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomaggeultext', '0006_auto_20201024_1126'),
        ('tomaggeultext', '0006_auto_20201024_1109'),
    ]

    operations = [
    ]
