# Generated by Django 3.1.1 on 2020-10-24 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomaggeultext', '0006_auto_20201024_1126 2'),
        ('tomaggeultext', '0007_merge_20201024_1335 2'),
        ('tomaggeultext', '0006_auto_20201024_1109 2'),
        ('tomaggeultext', '0007_merge_20201024_1335'),
    ]

    operations = [
    ]
