# Generated by Django 3.1.1 on 2020-10-24 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201024_1126'),
        ('user', '0002_auto_20201024_1109'),
    ]

    operations = [
    ]
